Repository Qovery/console, pull requests merged in 2023-08, with the labels that each got.

#728 feat(port-healthcheck): update on port settings for health checks
  libs/pages/application/src/lib/feature/page-settings-ports-feature/crud-modal-feature/crud-modal-feature.spec.tsx
  libs/pages/application/src/lib/feature/page-settings-ports-feature/crud-modal-feature/crud-modal-feature.tsx
  libs/pages/application/src/lib/feature/page-settings-ports-feature/page-settings-ports-feature.tsx
  libs/pages/application/src/lib/ui/page-settings-ports/page-settings-ports.tsx
  libs/shared/console-shared/src/index.ts
  libs/shared/console-shared/src/lib/flow-create-port/ui/crud-modal/crud-modal.spec.tsx
  libs/shared/console-shared/src/lib/flow-create-port/ui/crud-modal/crud-modal.tsx
  libs/shared/console-shared/src/lib/flow-create-port/ui/flow-create-port/flow-create-port.spec.tsx
  libs/shared/console-shared/src/lib/flow-create-port/ui/flow-create-port/flow-create-port.tsx
  libs/shared/console-shared/src/lib/flow-create-port/utils/port-healthcheck.spec.ts
  libs/shared/console-shared/src/lib/flow-create-port/utils/port-healthcheck.ts
  libs/shared/factories/src/lib/application-factory.mock.ts
  libs/shared/interfaces/src/lib/common/flow-port-data.interface.ts
  libs/shared/ui/src/lib/components/banner-box/banner-box.tsx
  libs/shared/ui/src/lib/components/inputs/input-select/input-select.spec.tsx
  libs/shared/ui/src/lib/components/inputs/input-select/input-select.tsx
Labels: enhancement

#733 fix(github-app): fix disconnection modal
  libs/pages/settings/src/lib/feature/page-organization-github-repository-access-feature/page-organization-github-repository-access-feature.tsx
Labels: bug

#736 fix(database): fix database metrics
  libs/pages/database/src/lib/page-database.tsx
  libs/pages/database/src/lib/ui/instances-table/instances-table.tsx
  libs/pages/database/src/lib/ui/page-general/page-general.tsx
Labels: bug

#731 tests: improve tests stack
  .eslintrc.json
  __tests__/mocks.ts
  __tests__/utils/setup-jest.tsx
  apps/console/src/main.tsx
  libs/pages/application/src/lib/feature/import-environment-variable-modal-feature/import-environment-variable-modal-feature.spec.tsx
  libs/pages/application/src/lib/ui/crud-environment-variable-modal/crud-environment-variable-modal.spec.tsx
  libs/pages/application/src/lib/ui/import-environment-variable-modal/import-environment-variable-modal.spec.tsx
  libs/pages/database/src/lib/feature/page-settings-resources-feature/page-settings-resources-feature.spec.tsx
  libs/shared/util-tests/.babelrc
  libs/shared/util-tests/.eslintrc.json
  libs/shared/util-tests/README.md
  libs/shared/util-tests/jest.config.ts
  libs/shared/util-tests/project.json
  libs/shared/util-tests/src/index.ts
  libs/shared/util-tests/src/lib/shared-util-tests.tsx
  libs/shared/util-tests/tsconfig.json
  libs/shared/util-tests/tsconfig.lib.json
  libs/shared/util-tests/tsconfig.spec.json
  libs/store/src/lib/root.ts
  nx.json
  package.json
  tsconfig.base.json
  yarn.lock
Labels: enhancement, dependencies

#738 fix(clone-service): remove name transformations
  libs/shared/console-shared/src/lib/clone-service-modal/ui/clone-service-modal.spec.tsx
  libs/shared/console-shared/src/lib/clone-service-modal/ui/clone-service-modal.tsx
Labels: bug

#729 feat(environment-logs): add deployment history
  libs/pages/logs/environment/src/lib/feature/deployment-logs-feature/deployment-logs-feature.spec.tsx
  libs/pages/logs/environment/src/lib/feature/deployment-logs-feature/deployment-logs-feature.tsx
  libs/pages/logs/environment/src/lib/feature/pod-logs-feature/pod-logs-feature.tsx
  libs/pages/logs/environment/src/lib/feature/service-stage-ids-context/service-stage-ids-context.spec.tsx
  libs/pages/logs/environment/src/lib/feature/service-stage-ids-context/service-stage-ids-context.tsx
  libs/pages/logs/environment/src/lib/feature/sidebar-history-feature/sidebar-history-feature.spec.tsx
  libs/pages/logs/environment/src/lib/feature/sidebar-history-feature/sidebar-history-feature.tsx
  libs/pages/logs/environment/src/lib/page-environment-logs.tsx
  libs/pages/logs/environment/src/lib/ui/deployment-logs/deployment-logs.spec.tsx
  libs/pages/logs/environment/src/lib/ui/deployment-logs/deployment-logs.tsx
  libs/pages/logs/environment/src/lib/ui/row-deployment/row-deployment.tsx
  libs/pages/logs/environment/src/lib/ui/row-pod/row-pod.tsx
  libs/pages/logs/environment/src/lib/ui/sidebar-history/sidebar-history.spec.tsx
  libs/pages/logs/environment/src/lib/ui/sidebar-history/sidebar-history.tsx
  libs/pages/logs/environment/src/lib/ui/sidebar-pipeline-item/sidebar-pipeline-item.tsx
  libs/pages/logs/environment/src/lib/ui/sidebar-pipeline/sidebar-pipeline.tsx
  libs/pages/logs/environment/src/lib/ui/sidebar-status/sidebar-status.tsx
  libs/pages/logs/environment/src/lib/ui/sidebar/sidebar.tsx
  libs/shared/console-shared/src/lib/layout-logs/layout-logs.tsx
  libs/shared/routes/src/lib/sub-router/logs.router.ts
  libs/shared/ui/src/lib/components/menu/menu.spec.tsx
  libs/shared/ui/src/lib/components/menu/menu.tsx
  libs/shared/ui/src/lib/styles/components/menu.scss
  libs/shared/utils/src/lib/tools/date.spec.ts
  libs/shared/utils/src/lib/tools/date.tsx
Labels: enhancement

#746 perf(ui): fix Menu rendering
  libs/shared/ui/src/lib/components/menu/menu.tsx
Labels: bug

#749 refactor(services): re-architecture domains layer
  libs/domains/services/README.md
  libs/domains/services/data-access/.eslintrc.json
  libs/domains/services/data-access/README.md
  libs/domains/services/data-access/jest.config.ts
  libs/domains/services/data-access/project.json
  libs/domains/services/data-access/src/index.ts
  libs/domains/services/data-access/src/lib/domains-services-data-access.ts
  libs/domains/services/data-access/tsconfig.json
  libs/domains/services/data-access/tsconfig.lib.json
  libs/domains/services/data-access/tsconfig.spec.json
  libs/domains/services/feature/.babelrc
  libs/domains/services/feature/.eslintrc.json
  libs/domains/services/feature/README.md
  libs/domains/services/feature/jest.config.ts
  libs/domains/services/feature/project.json
  libs/domains/services/feature/src/index.ts
  libs/domains/services/feature/src/lib/hooks/use-service-statuses/use-service-statuses.ts
  libs/domains/services/feature/src/lib/hooks/use-services/use-services.ts
  libs/domains/services/feature/src/lib/slices/services.queries.ts
  libs/domains/services/feature/tsconfig.json
  libs/domains/services/feature/tsconfig.lib.json
  libs/domains/services/feature/tsconfig.spec.json
  libs/domains/services/src/index.ts
  libs/shared/console-shared/src/lib/clone-service-modal/feature/clone-service-modal-feature.spec.tsx
  libs/shared/console-shared/src/lib/clone-service-modal/feature/clone-service-modal-feature.tsx
  libs/state/util-queries/src/index.ts
  libs/state/util-queries/src/lib/queries/queries.ts
  package.json
  tsconfig.base.json
  yarn.lock
Labels: enhancement

#750 chore: upgrade react query
  __tests__/utils/mock-use-query-result.tsx
  __tests__/utils/providers.tsx
  apps/console/src/main.tsx
  libs/domains/database/src/lib/slices/database.queries.ts
  libs/domains/environment/src/lib/slices/deployment-stage.ts
  libs/domains/environment/src/lib/slices/environment.actions.ts
  libs/domains/environment/src/lib/slices/environments.queries.ts
  libs/domains/event/src/lib/event.queries.ts
  libs/domains/organization/src/lib/slices/organization/organization.slice.ts
  libs/domains/services/feature/src/lib/hooks/use-service-statuses/use-service-statuses.ts
  libs/domains/services/feature/src/lib/hooks/use-services/use-services.ts
  libs/domains/services/feature/src/lib/slices/services.queries.ts
  libs/shared/util-tests/src/lib/shared-util-tests.tsx
  libs/shared/websockets/src/lib/components/cluster-web-socket/cluster-web-socket.tsx
  libs/state/util-queries/src/lib/use-react-query-ws-subscription/use-react-query-ws-subscription.spec.tsx
  libs/state/util-queries/src/lib/use-react-query-ws-subscription/use-react-query-ws-subscription.ts
  package.json
  yarn.lock
Labels: enhancement

#751 feat(deployment-row): add link to history logs
  libs/pages/application/src/lib/ui/page-deployments/page-deployments.tsx
  libs/pages/database/src/lib/ui/page-deployments/page-deployments.tsx
  libs/pages/services/src/lib/ui/page-deployments/page-deployments.tsx
  libs/shared/ui/src/lib/components/table/table-row-deployment/table-row-deployment.spec.tsx
  libs/shared/ui/src/lib/components/table/table-row-deployment/table-row-deployment.tsx
Labels: enhancement

#752 fix(modal-confirmation): modal disappear after actions
  libs/shared/ui/src/lib/components/modals/modal-confirmation/modal-confirmation.tsx
Labels: bug

#754 fix(override-var): fix missing scope in unwanted cases
  libs/pages/application/src/lib/feature/crud-environment-variable-modal-feature/crud-environment-variable-modal-feature.tsx
Labels: bug

#755 refactor(services): remove type alias
  libs/domains/services/data-access/src/lib/domains-services-data-access.ts
  package.json
  yarn.lock
Labels: enhancement

#753 feat(audit-logs): target link
  libs/pages/events/src/lib/ui/row-event/row-event.spec.tsx
  libs/pages/events/src/lib/ui/row-event/row-event.tsx
Labels: enhancement

#759 refactor(ui): move breadcrumb into pages-layout
  libs/pages/layout/src/lib/feature/breadcrumb/breadcrumb.tsx
  libs/pages/layout/src/lib/ui/breadcrumb-item/breadcrumb-item-value/breadcrumb-item-value.spec.tsx
  libs/pages/layout/src/lib/ui/breadcrumb-item/breadcrumb-item-value/breadcrumb-item-value.tsx
  libs/pages/layout/src/lib/ui/breadcrumb-item/breadcrumb-item.spec.tsx
  libs/pages/layout/src/lib/ui/breadcrumb-item/breadcrumb-item.tsx
  libs/pages/layout/src/lib/ui/breadcrumb/breadcrumb.spec.tsx
  libs/pages/layout/src/lib/ui/breadcrumb/breadcrumb.tsx
  libs/shared/ui/src/index.ts
Labels: enhancement

#768 perf: improve logs performances
  libs/pages/logs/environment/src/lib/feature/deployment-logs-feature/deployment-logs-feature.tsx
  libs/pages/logs/environment/src/lib/feature/pod-logs-feature/pod-logs-feature.tsx
Labels: enhancement

#776 fix(cluster-network): description field is required
  libs/pages/cluster/src/lib/ui/page-settings-network/crud-modal/crud-modal.tsx
Labels: bug

#744 feat(service): Use websocket for services status
  libs/domains/application/src/lib/slices/applications.slice.ts
  libs/domains/database/src/lib/slices/databases.slice.ts
  libs/domains/environment/src/lib/slices/environments.queries.ts
  libs/domains/environments/data-access/src/lib/domains-environments-data-access.ts
  libs/domains/environments/feature/src/index.ts
  libs/domains/environments/feature/src/lib/hooks/use-list-statuses/use-list-statuses.ts
  libs/domains/services/feature/src/index.ts
  libs/domains/services/feature/src/lib/hooks/use-deployment-status/use-deployment-status.ts
  libs/domains/services/feature/src/lib/service-deployment-status-label/service-deployment-status-label.tsx
  libs/pages/application/src/lib/feature/page-general-feature/page-general-feature.tsx
  libs/pages/application/src/lib/feature/tabs-feature/tabs-feature.tsx
  libs/pages/application/src/lib/page-application.tsx
  libs/pages/application/src/lib/ui/container/container.tsx
  libs/pages/clusters/src/lib/feature/page-clusters-general-feature/page-clusters-general-feature.tsx
  libs/pages/database/src/lib/page-database.tsx
  libs/pages/database/src/lib/ui/container/container.tsx
  libs/pages/database/src/lib/ui/page-general/page-general.tsx
  libs/pages/environments/src/lib/feature/page-general-feature/page-general-feature.spec.tsx
  libs/pages/environments/src/lib/feature/page-general-feature/page-general-feature.tsx
  libs/pages/environments/src/lib/ui/page-general/page-general.spec.tsx
  libs/pages/environments/src/lib/ui/page-general/page-general.tsx
  libs/pages/environments/src/lib/ui/table-row-environments/table-row-environments.tsx
  libs/pages/layout/src/lib/feature/breadcrumb/breadcrumb.tsx
  libs/pages/layout/src/lib/feature/layout/layout.tsx
  libs/pages/layout/src/lib/ui/breadcrumb/breadcrumb.tsx
  libs/pages/logs/environment/src/lib/feature/deployment-logs-feature/deployment-logs-feature.tsx
  libs/pages/logs/environment/src/lib/page-environment-logs.tsx
  libs/pages/logs/environment/src/lib/ui/deployment-logs/deployment-logs.tsx
  libs/pages/logs/environment/src/lib/ui/pod-logs/pod-logs.tsx
  libs/pages/services/src/lib/feature/page-general-feature/page-general-feature.spec.tsx
  libs/pages/services/src/lib/feature/page-general-feature/page-general-feature.tsx
  libs/pages/services/src/lib/feature/page-settings-danger-zone-feature/page-settings-danger-zone-feature.tsx
  libs/pages/services/src/lib/page-services.tsx
  libs/pages/services/src/lib/ui/container/container.tsx
  libs/pages/services/src/lib/ui/page-general/page-general.spec.tsx
  libs/pages/services/src/lib/ui/page-general/page-general.tsx
  libs/pages/services/src/lib/ui/table-row-services/table-row-services.tsx
  libs/shared/console-shared/src/lib/buttons-actions/ui/application-buttons-actions/application-buttons-actions.spec.tsx
  libs/shared/console-shared/src/lib/buttons-actions/ui/application-buttons-actions/application-buttons-actions.tsx
  libs/shared/console-shared/src/lib/buttons-actions/ui/database-buttons-actions/database-buttons-actions.spec.tsx
  libs/shared/console-shared/src/lib/buttons-actions/ui/database-buttons-actions/database-buttons-actions.tsx
  libs/shared/console-shared/src/lib/buttons-actions/ui/environment-buttons-actions/environment-buttons-actions.spec.tsx
  libs/shared/console-shared/src/lib/buttons-actions/ui/environment-buttons-actions/environment-buttons-actions.tsx
  libs/shared/console-shared/src/lib/layout-logs/layout-logs.tsx
  libs/shared/console-shared/src/lib/need-redeploy-flag/ui/need-redeploy-flag.spec.tsx
  libs/shared/console-shared/src/lib/need-redeploy-flag/ui/need-redeploy-flag.tsx
  libs/shared/factories/src/lib/container-factory.mock.ts
  libs/shared/interfaces/src/lib/domain/container-application.entity.ts
  libs/shared/interfaces/src/lib/domain/database.entity.ts
  libs/shared/interfaces/src/lib/domain/git-application.entity.ts
  libs/shared/interfaces/src/lib/domain/job-application.entity.ts
  libs/shared/util-web-sockets/src/lib/use-status-web-sockets/use-status-web-sockets.ts
  libs/shared/utils/src/lib/hooks/use-running-status-websocket/use-running-status-websocket.tsx
  libs/shared/utils/src/lib/tools/refacto-payload.spec.ts
  libs/shared/websockets/src/lib/components/websocket-container/websocket-container.tsx
  libs/state/util-queries/src/lib/use-react-query-ws-subscription/use-react-query-ws-subscription.ts
Labels: enhancement
