Repository Qovery/console, pull requests merged in 2023-07, with the labels that each got.

#679 feat(modal-confirmation-delete): change confirm deletion modal
  libs/pages/application/src/lib/feature/page-settings-domains-feature/page-settings-domains-feature.tsx
  libs/pages/application/src/lib/feature/page-settings-ports-feature/page-settings-ports-feature.tsx
  libs/pages/application/src/lib/feature/page-settings-storage-feature/page-settings-storage-feature.tsx
  libs/pages/application/src/lib/feature/table-row-environment-variable-feature/table-row-environment-variable-feature.tsx
  libs/pages/application/src/lib/ui/page-settings-danger-zone/page-settings-danger-zone.tsx
  libs/pages/cluster/src/lib/feature/page-settings-network-feature/page-settings-network-feature.tsx
  libs/pages/cluster/src/lib/ui/page-settings-danger-zone/page-settings-danger-zone.tsx
  libs/pages/database/src/lib/ui/page-settings-danger-zone/page-settings-danger-zone.tsx
  libs/pages/services/src/lib/feature/page-settings-deployment-pipeline-feature/page-settings-deployment-pipeline-feature.tsx
  libs/pages/services/src/lib/ui/page-settings-danger-zone/page-settings-danger-zone.tsx
  libs/pages/settings/src/lib/feature/page-organization-api-feature/page-organization-api-feature.tsx
  libs/pages/settings/src/lib/feature/page-organization-billing-feature/page-organization-billing-feature.tsx
  libs/pages/settings/src/lib/feature/page-organization-container-registries-feature/page-organization-container-registries-feature.tsx
  libs/pages/settings/src/lib/feature/page-organization-roles-edit-feature/page-organization-roles-edit-feature.tsx
  libs/pages/settings/src/lib/feature/page-organization-webhooks-feature/page-organization-webhooks-feature.tsx
  libs/pages/settings/src/lib/ui/page-organization-danger-zone/page-organization-danger-zone.tsx
  libs/pages/settings/src/lib/ui/page-organization-members/row-member/row-member.tsx
  libs/pages/settings/src/lib/ui/page-project-danger-zone/page-project-danger-zone.tsx
  libs/shared/console-shared/src/lib/buttons-actions/ui/application-buttons-actions/application-buttons-actions.tsx
  libs/shared/console-shared/src/lib/buttons-actions/ui/cluster-buttons-actions/cluster-buttons-actions.tsx
  libs/shared/console-shared/src/lib/buttons-actions/ui/database-buttons-actions/database-buttons-actions.tsx
  libs/shared/console-shared/src/lib/environment-buttons-actions/ui/environment-buttons-actions.tsx
  libs/shared/ui/src/lib/components/block-content-delete/block-content-delete.tsx
  libs/shared/ui/src/lib/components/modals/modal-confirmation/__snapshots__/modal-confirmation.spec.tsx.snap
  libs/shared/ui/src/lib/components/modals/modal-confirmation/modal-confirmation.spec.tsx
  libs/shared/ui/src/lib/components/modals/modal-confirmation/modal-confirmation.stories.tsx
  libs/shared/ui/src/lib/components/modals/modal-confirmation/modal-confirmation.tsx
  libs/shared/ui/src/lib/components/modals/modal-confirmation/use-modal-confirmation/use-modal-confirmation.tsx
Labels: enhancement

#686 chore(package.json): update yarn test command
  apps/console/src/app/app.spec.tsx
  package.json
Labels: enhancement

#687 chore: fix gitignore
  .gitignore
Labels: enhancement

#688 chore: add editorconfig
  .editorconfig
Labels: enhancement

#676 feat(audit-logs): add filter with context
  libs/domains/environment-variable/src/lib/slices/environment-variables.slice.ts
  libs/domains/environment-variable/src/lib/slices/secret-environment-variables.slice.ts
  libs/domains/event/src/lib/event.queries.ts
  libs/pages/events/src/lib/feature/custom-filter-feature/custom-filter-feature.spec.tsx
  libs/pages/events/src/lib/feature/custom-filter-feature/custom-filter-feature.tsx
  libs/pages/events/src/lib/feature/page-general-feature/page-general-feature.tsx
  libs/pages/events/src/lib/ui/custom-filter/custom-filter.spec.tsx
  libs/pages/events/src/lib/ui/custom-filter/custom-filter.tsx
  libs/pages/events/src/lib/ui/page-general/page-general.spec.tsx
  libs/pages/events/src/lib/ui/page-general/page-general.tsx
  libs/shared/ui/src/lib/components/inputs/input-filter/__snapshots__/input-filter.spec.tsx.snap
  libs/shared/ui/src/lib/components/inputs/input-filter/input-filter.spec.tsx
  libs/shared/ui/src/lib/components/inputs/input-filter/input-filter.tsx
  package.json
  yarn.lock
Labels: enhancement

#680 feat(warn-instance-number): add warning on instance number
  libs/pages/application/src/lib/feature/page-settings-healthchecks-feature/page-settings-healthchecks-feature.tsx
  libs/pages/application/src/lib/ui/page-settings-healthchecks/page-settings-healthchecks.spec.tsx
  libs/pages/application/src/lib/ui/page-settings-healthchecks/page-settings-healthchecks.tsx
  libs/shared/console-shared/src/lib/application-settings/ui/application-settings-resources/application-settings-resources.tsx
Labels: enhancement

#691 ci: align with NX CI standards
  .github/workflows/nx-cloud-main.yml
  .github/workflows/test-build-and-deploy.yml
Labels: enhancement

#692 chore: fix dependencies
  Dockerfile
  nx.json
  package.json
  yarn.lock
Labels: dependencies

#693 chore: enable nginx compression
  nginx.conf
Labels: enhancement

#695 chore: add vscode settings & extensions
  .vscode/extensions.json
  .vscode/settings.json
Labels: enhancement

#675 chore: move to yarn berry
  .yarn/releases/yarn-berry.cjs
  .yarnrc.yml
  Dockerfile
  Storybook
  package.json
  yarn.lock
Labels: dependencies

#697 chore(environments-queries): update environment by id query
  libs/domains/environment/src/index.ts
  libs/domains/environment/src/lib/slices/environments.queries.ts
  libs/pages/application/src/lib/feature/page-settings-danger-zone-feature/page-settings-danger-zone-feature.tsx
  libs/pages/application/src/lib/feature/page-settings-healthchecks-feature/page-settings-healthchecks-feature.tsx
  libs/pages/application/src/lib/feature/page-settings-resources-feature/page-settings-resources-feature.tsx
  libs/pages/application/src/lib/page-application.tsx
  libs/pages/application/src/lib/ui/page-settings-healthchecks/page-settings-healthchecks.tsx
  libs/pages/application/src/lib/ui/page-settings-resources/page-settings-resources.tsx
  libs/pages/database/src/lib/feature/page-settings-danger-zone-feature/page-settings-danger-zone-feature.tsx
  libs/pages/database/src/lib/feature/page-settings-general-feature/page-settings-general-feature.tsx
  libs/pages/database/src/lib/feature/page-settings-resources-feature/page-settings-resources-feature.tsx
  libs/pages/database/src/lib/page-database.tsx
  libs/pages/logs/environment/src/lib/page-environment-logs.tsx
  libs/pages/services/src/lib/feature/page-application-create-feature/step-resources-feature/step-resources-feature.tsx
  libs/pages/services/src/lib/feature/page-database-create-feature/step-general-feature/step-general-feature.tsx
  libs/pages/services/src/lib/feature/page-deployments-feature/page-deployments-feature.tsx
  libs/pages/services/src/lib/feature/page-general-feature/page-general-feature.tsx
  libs/pages/services/src/lib/feature/page-job-create-feature/step-resources-feature/step-resources-feature.tsx
  libs/pages/services/src/lib/feature/page-settings-danger-zone-feature/page-settings-danger-zone-feature.tsx
  libs/pages/services/src/lib/feature/page-settings-deployment-pipeline-feature/page-settings-deployment-pipeline-feature.tsx
  libs/pages/services/src/lib/feature/page-settings-general-feature/page-settings-general-feature.tsx
  libs/pages/services/src/lib/page-services.tsx
  libs/pages/services/src/lib/ui/page-application-create/step-resources/step-resources.tsx
  libs/pages/services/src/lib/ui/page-job-create/step-resources/step-resources.tsx
  libs/shared/console-shared/src/lib/application-settings/ui/application-settings-resources/application-settings-resources.tsx
  libs/shared/console-shared/src/lib/database-settings-resources/feature/settings-resources-instance-types-feature/setting-resources-instance-types-feature.tsx
  libs/shared/console-shared/src/lib/update-all-modal/feature/update-all-modal-feature.tsx
Labels: breaking change

#699 fix(warn-instance-number): fix warning condition
  libs/pages/application/src/lib/feature/page-settings-healthchecks-feature/page-settings-healthchecks-feature.tsx
  libs/pages/application/src/lib/ui/page-settings-healthchecks/page-settings-healthchecks.tsx
  libs/shared/console-shared/src/lib/application-settings/ui/application-settings-resources/application-settings-resources.tsx
Labels: bug

#700 feat(clone-service): add clone service feature
  libs/domains/services/.babelrc
  libs/domains/services/.eslintrc.json
  libs/domains/services/README.md
  libs/domains/services/jest.config.ts
  libs/domains/services/project.json
  libs/domains/services/src/index.ts
  libs/domains/services/src/lib/slices/services.queries.ts
  libs/domains/services/tsconfig.json
  libs/domains/services/tsconfig.lib.json
  libs/domains/services/tsconfig.spec.json
  libs/shared/console-shared/src/lib/buttons-actions/ui/application-buttons-actions/application-buttons-actions.tsx
  libs/shared/console-shared/src/lib/buttons-actions/ui/database-buttons-actions/database-buttons-actions.tsx
  libs/shared/console-shared/src/lib/clone-service-modal/feature/clone-service-modal-feature.spec.tsx
  libs/shared/console-shared/src/lib/clone-service-modal/feature/clone-service-modal-feature.tsx
  libs/shared/console-shared/src/lib/clone-service-modal/ui/clone-service-modal.spec.tsx
  libs/shared/console-shared/src/lib/clone-service-modal/ui/clone-service-modal.tsx
  libs/shared/factories/src/lib/environment-factory.mock.ts
  package.json
  tsconfig.base.json
Labels: enhancement
